name: hobby_hub_ui
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  cached_network_image: ^2.2.0+1
  material_design_icons_flutter: ^4.0.5345
  provider: ^5.0.0
  http: ^0.13.1
  form_field_validator: ^1.1.0
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  multi_select_flutter: ^4.0.0
  timeago: ^3.0.2
  flutter_spinkit: ^5.0.0
  liquid_pull_to_refresh: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

